trigger:
- main

stages:

# =========================
# BUILD
# =========================
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Npm@1
      inputs:
        command: 'install'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'


# =========================
# DEPLOY
# =========================
- stage: Deploy
  dependsOn: Build

  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(926dc45b-bfb6-47ff-9117-1e38a3c1d32a)'
        appType: 'webAppLinux'
        WebAppName: 'devopsaidavali'
        packageForLinux: '$(System.ArtifactsDirectory)/drop'
        RuntimeStack: 'STATICSITE|1.0'
        DeploymentTypeLinux: 'oneDeploy'